# Generated by Django 2.1.7 on 2019-09-25 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logandreg1', '0003_auto_20190925_1438'),
        ('pythonexam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='group',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='group',
            name='user_groups',
        ),
        migrations.AddField(
            model_name='group',
            name='joined_users',
            field=models.ManyToManyField(related_name='joined_groups', to='logandreg1.Registration'),
        ),
        migrations.AlterField(
            model_name='group',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='logandreg1.Registration'),
        ),
    ]
