# Generated by Django 2.1.7 on 2019-09-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonexam', '0002_auto_20190925_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='desc',
            field=models.TextField(default='bob'),
            preserve_default=False,
        ),
    ]
