# Generated by Django 2.1.7 on 2019-09-24 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_follow_friend_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='friend',
            new_name='like',
        ),
        migrations.AddField(
            model_name='follow',
            name='user_fav_follow',
            field=models.ManyToManyField(related_name='fav_follow', to='login.User'),
        ),
        migrations.AddField(
            model_name='friend',
            name='user_fav_friend',
            field=models.ManyToManyField(related_name='fav_friend', to='login.User'),
        ),
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='like_post', to='login.User'),
        ),
        migrations.AddField(
            model_name='like',
            name='user_fav_like',
            field=models.ManyToManyField(related_name='fav_like', to='login.User'),
        ),
        migrations.RemoveField(
            model_name='follow',
            name='user',
        ),
        migrations.AddField(
            model_name='follow',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follower', to='login.User'),
        ),
        migrations.RemoveField(
            model_name='friend',
            name='user',
        ),
        migrations.AddField(
            model_name='friend',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friends', to='login.User'),
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='like_user', to='login.User'),
        ),
    ]
