# Generated by Django 2.1.7 on 2019-09-26 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20190926_1219'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupchat',
            name='member_Groupchat',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='groupchat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='groupchat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user_like',
        ),
        migrations.AddField(
            model_name='message',
            name='users_liked',
            field=models.ManyToManyField(related_name='liked_messages', to='login.User'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_invites', to='login.User'),
        ),
        migrations.DeleteModel(
            name='GroupChat',
        ),
    ]
