# Generated by Django 2.1.7 on 2019-09-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20190926_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='other_name',
            field=models.CharField(default='ble', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='real_name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
    ]
