# Generated by Django 2.1.7 on 2019-09-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20190926_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='other_name',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='real_name',
        ),
        migrations.AddField(
            model_name='chat',
            name='other_id',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='real_id',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
