# Generated by Django 2.1.7 on 2019-09-26 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20190926_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='invite_reason',
        ),
    ]
