# Generated by Django 2.1.7 on 2019-09-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20190926_1219'),
        ('chat', '0005_remove_friendship_invite_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='members_chat',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='name',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='other_id',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='real_id',
        ),
        migrations.AddField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(to='login.User'),
        ),
    ]
