# Generated by Django 2.1.7 on 2019-09-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20190927_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='inviter',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='user',
        ),
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(default='user', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='friendship',
        ),
    ]
