# Generated by Django 2.1.7 on 2019-09-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logandreg1', '0002_remove_registration_confirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='lastname',
        ),
        migrations.AddField(
            model_name='registration',
            name='name',
            field=models.CharField(default='bob', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(max_length=150),
        ),
    ]
