# Generated by Django 2.1.7 on 2019-09-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190918_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='rannicy', max_length=100),
            preserve_default=False,
        ),
    ]
