# Generated by Django 2.1.7 on 2019-09-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Show',
            new_name='User',
        ),
    ]
