# Generated by Django 2.1.7 on 2019-09-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='notes',
            field=models.TextField(default='dont read this book'),
            preserve_default=False,
        ),
    ]
