# Generated by Django 2.1.7 on 2019-09-17 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_tvshow', '0002_auto_20190917_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='Network',
            new_name='network',
        ),
    ]
