# Generated by Django 2.1.7 on 2019-09-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_tvshow', '0004_auto_20190917_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.CharField(max_length=100),
        ),
    ]
